name: Build APK

on:
  push:
    branches:
      - '*'
      - 'refactor/ci/improve-workflows'
    paths-ignore:
      - '**.md'
      - '.idea/*'
      - 'LICENSE'
      - 'FUNDING.yml'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.idea/*'
      - 'LICENSE'
      - 'FUNDING.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build debug APK
        run: ./gradlew :app:android:assembleDebug

      - name: Decode keystore
        if: (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch') && secrets.KEYSTORE_BASE64 != ''
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore/release.jks

      - name: Build release APK
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: ./gradlew :app:android:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_FILE: ${{ secrets.SIGNING_STORE_FILE }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: gloom-debug
          path: app/android/build/outputs/apk/debug/gloom-debug.apk

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        with:
          name: gloom-release
          path: app/android/build/outputs/apk/release/gloom-release.apk