name: Lint Project Source

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Lint with Detekt
        run:
          ./gradlew detekt

      - uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: ui/build/reports/detekt/detekt.sarif
          category: ui